//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSS_Website.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HSS_Website.ServiceReference1.Users))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.HouseOccupant HouseOccupantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.HouseOwner HouseOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.Respondent RespondentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.Table TableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.HouseOccupant HouseOccupant {
            get {
                return this.HouseOccupantField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseOccupantField, value) != true)) {
                    this.HouseOccupantField = value;
                    this.RaisePropertyChanged("HouseOccupant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.HouseOwner HouseOwner {
            get {
                return this.HouseOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseOwnerField, value) != true)) {
                    this.HouseOwnerField = value;
                    this.RaisePropertyChanged("HouseOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Number {
            get {
                return this.ID_NumberField;
            }
            set {
                if ((this.ID_NumberField.Equals(value) != true)) {
                    this.ID_NumberField = value;
                    this.RaisePropertyChanged("ID_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.Respondent Respondent {
            get {
                return this.RespondentField;
            }
            set {
                if ((object.ReferenceEquals(this.RespondentField, value) != true)) {
                    this.RespondentField = value;
                    this.RaisePropertyChanged("Respondent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.Table Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseOccupant", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class HouseOccupant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HouseOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.HouseOwner HouseOwner1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HouseOwner {
            get {
                return this.HouseOwnerField;
            }
            set {
                if ((this.HouseOwnerField.Equals(value) != true)) {
                    this.HouseOwnerField = value;
                    this.RaisePropertyChanged("HouseOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.HouseOwner HouseOwner1 {
            get {
                return this.HouseOwner1Field;
            }
            set {
                if ((object.ReferenceEquals(this.HouseOwner1Field, value) != true)) {
                    this.HouseOwner1Field = value;
                    this.RaisePropertyChanged("HouseOwner1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseOwner", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class HouseOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HouseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.HouseOccupant[] HouseOccupantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.Package PackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PackageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HouseID {
            get {
                return this.HouseIDField;
            }
            set {
                if ((this.HouseIDField.Equals(value) != true)) {
                    this.HouseIDField = value;
                    this.RaisePropertyChanged("HouseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.HouseOccupant[] HouseOccupants {
            get {
                return this.HouseOccupantsField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseOccupantsField, value) != true)) {
                    this.HouseOccupantsField = value;
                    this.RaisePropertyChanged("HouseOccupants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.Package Package {
            get {
                return this.PackageField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageField, value) != true)) {
                    this.PackageField = value;
                    this.RaisePropertyChanged("Package");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PackageID {
            get {
                return this.PackageIDField;
            }
            set {
                if ((this.PackageIDField.Equals(value) != true)) {
                    this.PackageIDField = value;
                    this.RaisePropertyChanged("PackageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respondent", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class Respondent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LattituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Lattitute {
            get {
                return this.LattituteField;
            }
            set {
                if ((this.LattituteField.Equals(value) != true)) {
                    this.LattituteField = value;
                    this.RaisePropertyChanged("Lattitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitute {
            get {
                return this.LongituteField;
            }
            set {
                if ((this.LongituteField.Equals(value) != true)) {
                    this.LongituteField = value;
                    this.RaisePropertyChanged("Longitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LattituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Lattitute {
            get {
                return this.LattituteField;
            }
            set {
                if ((this.LattituteField.Equals(value) != true)) {
                    this.LattituteField = value;
                    this.RaisePropertyChanged("Lattitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitute {
            get {
                return this.LongituteField;
            }
            set {
                if ((this.LongituteField.Equals(value) != true)) {
                    this.LongituteField = value;
                    this.RaisePropertyChanged("Longitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class Users : HSS_Website.ServiceReference1.User {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HSS_Website.ServiceReference1.HouseOwner[] HouseOwnersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PackageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HSS_Website.ServiceReference1.HouseOwner[] HouseOwners {
            get {
                return this.HouseOwnersField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseOwnersField, value) != true)) {
                    this.HouseOwnersField = value;
                    this.RaisePropertyChanged("HouseOwners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackageID {
            get {
                return this.PackageIDField;
            }
            set {
                if ((this.PackageIDField.Equals(value) != true)) {
                    this.PackageIDField = value;
                    this.RaisePropertyChanged("PackageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="House", Namespace="http://schemas.datacontract.org/2004/07/TempServe")]
    [System.SerializableAttribute()]
    public partial class House : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HouseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HouseNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LattituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongituteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HouseID {
            get {
                return this.HouseIDField;
            }
            set {
                if ((this.HouseIDField.Equals(value) != true)) {
                    this.HouseIDField = value;
                    this.RaisePropertyChanged("HouseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HouseNo {
            get {
                return this.HouseNoField;
            }
            set {
                if ((this.HouseNoField.Equals(value) != true)) {
                    this.HouseNoField = value;
                    this.RaisePropertyChanged("HouseNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Lattitute {
            get {
                return this.LattituteField;
            }
            set {
                if ((this.LattituteField.Equals(value) != true)) {
                    this.LattituteField = value;
                    this.RaisePropertyChanged("Lattitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitute {
            get {
                return this.LongituteField;
            }
            set {
                if ((this.LongituteField.Equals(value) != true)) {
                    this.LongituteField = value;
                    this.RaisePropertyChanged("Longitute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surburb {
            get {
                return this.SurburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SurburbField, value) != true)) {
                    this.SurburbField = value;
                    this.RaisePropertyChanged("Surburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIPCode {
            get {
                return this.ZIPCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPCodeField, value) != true)) {
                    this.ZIPCodeField = value;
                    this.RaisePropertyChanged("ZIPCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNearestRespondent", ReplyAction="http://tempuri.org/IService1/GetNearestRespondentResponse")]
        string GetNearestRespondent(int userID, double lattitude, double longitute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNearestRespondent", ReplyAction="http://tempuri.org/IService1/GetNearestRespondentResponse")]
        System.Threading.Tasks.Task<string> GetNearestRespondentAsync(int userID, double lattitude, double longitute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        HSS_Website.ServiceReference1.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<HSS_Website.ServiceReference1.User> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        void Register(HSS_Website.ServiceReference1.User user, HSS_Website.ServiceReference1.House house);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(HSS_Website.ServiceReference1.User user, HSS_Website.ServiceReference1.House house);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistanceBetweenPoints", ReplyAction="http://tempuri.org/IService1/GetDistanceBetweenPointsResponse")]
        double GetDistanceBetweenPoints(double p1Lattitute, double p1Longitute, double p2Lattitute, double p2Longitute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistanceBetweenPoints", ReplyAction="http://tempuri.org/IService1/GetDistanceBetweenPointsResponse")]
        System.Threading.Tasks.Task<double> GetDistanceBetweenPointsAsync(double p1Lattitute, double p1Longitute, double p2Lattitute, double p2Longitute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        HSS_Website.ServiceReference1.User GetUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<HSS_Website.ServiceReference1.User> GetUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHouse", ReplyAction="http://tempuri.org/IService1/GetHouseResponse")]
        HSS_Website.ServiceReference1.House GetHouse(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHouse", ReplyAction="http://tempuri.org/IService1/GetHouseResponse")]
        System.Threading.Tasks.Task<HSS_Website.ServiceReference1.House> GetHouseAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHouseOccupants", ReplyAction="http://tempuri.org/IService1/GetHouseOccupantsResponse")]
        HSS_Website.ServiceReference1.Users[] GetHouseOccupants(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHouseOccupants", ReplyAction="http://tempuri.org/IService1/GetHouseOccupantsResponse")]
        System.Threading.Tasks.Task<HSS_Website.ServiceReference1.Users[]> GetHouseOccupantsAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHouseOccupant", ReplyAction="http://tempuri.org/IService1/AddHouseOccupantResponse")]
        bool AddHouseOccupant(HSS_Website.ServiceReference1.Users houseoccupant, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHouseOccupant", ReplyAction="http://tempuri.org/IService1/AddHouseOccupantResponse")]
        System.Threading.Tasks.Task<bool> AddHouseOccupantAsync(HSS_Website.ServiceReference1.Users houseoccupant, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveHouseOccupant", ReplyAction="http://tempuri.org/IService1/RemoveHouseOccupantResponse")]
        bool RemoveHouseOccupant(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveHouseOccupant", ReplyAction="http://tempuri.org/IService1/RemoveHouseOccupantResponse")]
        System.Threading.Tasks.Task<bool> RemoveHouseOccupantAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPackage", ReplyAction="http://tempuri.org/IService1/AddPackageResponse")]
        bool AddPackage(int userID, int packageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPackage", ReplyAction="http://tempuri.org/IService1/AddPackageResponse")]
        System.Threading.Tasks.Task<bool> AddPackageAsync(int userID, int packageID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HSS_Website.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HSS_Website.ServiceReference1.IService1>, HSS_Website.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNearestRespondent(int userID, double lattitude, double longitute) {
            return base.Channel.GetNearestRespondent(userID, lattitude, longitute);
        }
        
        public System.Threading.Tasks.Task<string> GetNearestRespondentAsync(int userID, double lattitude, double longitute) {
            return base.Channel.GetNearestRespondentAsync(userID, lattitude, longitute);
        }
        
        public HSS_Website.ServiceReference1.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<HSS_Website.ServiceReference1.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Register(HSS_Website.ServiceReference1.User user, HSS_Website.ServiceReference1.House house) {
            base.Channel.Register(user, house);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(HSS_Website.ServiceReference1.User user, HSS_Website.ServiceReference1.House house) {
            return base.Channel.RegisterAsync(user, house);
        }
        
        public double GetDistanceBetweenPoints(double p1Lattitute, double p1Longitute, double p2Lattitute, double p2Longitute) {
            return base.Channel.GetDistanceBetweenPoints(p1Lattitute, p1Longitute, p2Lattitute, p2Longitute);
        }
        
        public System.Threading.Tasks.Task<double> GetDistanceBetweenPointsAsync(double p1Lattitute, double p1Longitute, double p2Lattitute, double p2Longitute) {
            return base.Channel.GetDistanceBetweenPointsAsync(p1Lattitute, p1Longitute, p2Lattitute, p2Longitute);
        }
        
        public HSS_Website.ServiceReference1.User GetUser(int ID) {
            return base.Channel.GetUser(ID);
        }
        
        public System.Threading.Tasks.Task<HSS_Website.ServiceReference1.User> GetUserAsync(int ID) {
            return base.Channel.GetUserAsync(ID);
        }
        
        public HSS_Website.ServiceReference1.House GetHouse(int ID) {
            return base.Channel.GetHouse(ID);
        }
        
        public System.Threading.Tasks.Task<HSS_Website.ServiceReference1.House> GetHouseAsync(int ID) {
            return base.Channel.GetHouseAsync(ID);
        }
        
        public HSS_Website.ServiceReference1.Users[] GetHouseOccupants(int ID) {
            return base.Channel.GetHouseOccupants(ID);
        }
        
        public System.Threading.Tasks.Task<HSS_Website.ServiceReference1.Users[]> GetHouseOccupantsAsync(int ID) {
            return base.Channel.GetHouseOccupantsAsync(ID);
        }
        
        public bool AddHouseOccupant(HSS_Website.ServiceReference1.Users houseoccupant, int ID) {
            return base.Channel.AddHouseOccupant(houseoccupant, ID);
        }
        
        public System.Threading.Tasks.Task<bool> AddHouseOccupantAsync(HSS_Website.ServiceReference1.Users houseoccupant, int ID) {
            return base.Channel.AddHouseOccupantAsync(houseoccupant, ID);
        }
        
        public bool RemoveHouseOccupant(int ID) {
            return base.Channel.RemoveHouseOccupant(ID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveHouseOccupantAsync(int ID) {
            return base.Channel.RemoveHouseOccupantAsync(ID);
        }
        
        public bool AddPackage(int userID, int packageID) {
            return base.Channel.AddPackage(userID, packageID);
        }
        
        public System.Threading.Tasks.Task<bool> AddPackageAsync(int userID, int packageID) {
            return base.Channel.AddPackageAsync(userID, packageID);
        }
    }
}
